name: CI - Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          software-properties-common \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libwebkit2gtk-4.1-dev

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install nsis

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Test Build
        run: cargo tauri build
