name: CI - Build Test

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/build-test.yml
      - .github/ISSUE_TEMPLATE/**
      - README.md
      - LICENSE

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Tauri build pipeline
        uses: tauri-apps/tauri-action@v0.5.0
        with:
          projectPath: .
          cache: true
          packages: npm
