name: CI - Code Quality

on:
  push:
    paths-ignore:
      - .github/workflows/ci.yml
      - .github/ISSUE_TEMPLATE/**
      - README.md
      - LICENSE
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run TypeScript Check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint 'src/**/*.{js,ts,jsx,tsx}' --max-warnings=0

      - name: Run Prettier Check
        run: npx prettier --check 'src/**/*.{js,ts,jsx,tsx}'
