name: Test Coverage

on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: 'Install Deps'
        run: npm install

      - name: 'Run Tests'
        run: npx vitest --coverage.enabled true
      
      - name: 'Report Coverage'
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2

      